SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720


ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 1.5  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED_MAX = 400
PLAYER_SPEED_MAX_BACK = -300
PLAYER_SPEED_THRESHOLD = 150
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
